/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

@IsTest
public class PaymentTransactionTest {
//    static testMethod void checkTransaction(){
//        	User u1 = [SELECT id FROM User WHERE id = '00511000004rIw6'];
//        	System.runAs(u1){
//                Contact testContact = new Contact(LastName = 'TestContact');
//                insert testContact;
//                Charge_Group__c test = new Charge_Group__c(Guarantor__c = testContact.id);
//                insert test;
//                Id val;
//                val = 'a0R11000006dbFNEAY';
//                Transaction__c newTr = new Transaction__c(Sirono_ID__c=22148106, Name='credit-22148106', Notes__c='', Credit_Balance__c=false, Charge_Group__c=val);
//        		insert newTr;
//            }
//    }
}