/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * An apex page controller that exposes the change password functionality
 */
public with sharing class ChangePasswordController {

    public ChangePasswordController() {
    } //Delete this line when the below code is uncommented.
    /*
    public String oldPassword {get; set;}
    public String newPassword {get; set;}
    public String verifyNewPassword {get; set;}        
    
    public ChangePasswordController() {}
	
	//Controller Method that sets new password     
    public PageReference changePassword() {
        return Site.changePassword(newPassword, verifyNewPassword, oldpassword);    
    }   
*/


}