/*
 * @author: Sirono
 * @version 1.0.1
 * @Date: 05-03-2016 
 * An apex page controller that exposes the change password functionality
 * 
 * 14/09/2016 commented the code since it is not used into community/site for any business requirement 
 */

public with sharing class ChangePasswordController {

    public ChangePasswordController() {
    } //Delete this line when the below code is uncommented.
    /*
    public String oldPassword {get; set;}
    public String newPassword {get; set;}
    public String verifyNewPassword {get; set;}        
    
    public ChangePasswordController() {}
	
	//Controller Method that sets new password     
    public PageReference changePassword() {
        return Site.changePassword(newPassword, verifyNewPassword, oldpassword);    
    }   
*/


}