/*
* @author: Sirono
* @version 1.0.1
* @Date: 05-09-2016
* @description  wrapper class
*/

public with sharing class ChargeGroupWrapper {
    public ChargeGroupWrapper() {
    
    }
	/*public Charge_Group__c cg {get; set;}
    public Boolean isSelected {get; set;}

    //Constructor initializing the wrapper class variables
    public ChargeGroupWrapper(Charge_Group__c cg, Boolean isSelected) {
        this.cg = cg;
        this.isSelected = isSelected;
    }*/
}