/*
 * @author: Sirono
 * @version 1.0.1
 * @Date: 05-03-2016  
 * @description An apex page controller that takes the user to the right start page based on credentials or lack thereof
 * 
 * 14/09/2016 commented the code since it is not used into community/site for any business requirement 
 */
public with sharing class CommunitiesSelfRegConfirmController {

    public CommunitiesSelfRegConfirmController() {
    }

}