/**
 * Created by justindove on 11/29/16.
 */

public class Constants {

    public static final String ACCT_SUBSTATUS_DUE_BY = 'Due By';
    public static final String ACCT_SUBSTATUS_PAYMENT_PLAN = 'On Payment Plan';
    public static final String ACCT_SUBSTATUS_INACTIVE = 'Inactive';
    public static final String ACCT_SUBSTATUS_OVERDUE = 'Overdue';
    public static final String ACCT_SUBSTATUS_DELINQUENT = 'Delinquent';
    public static final String ACCT_SUBSTATUS_BAD_DEBT = 'Bad Debt';
    public static final String ACCT_SUBSTATUS_OPEN = 'Open';
    public static final String ACCT_SUBSTATUS_DNFB = 'Pending Billing';
    public static final String ACCT_SUBSTATUS_PENDING_INS = 'Pending Insurance';
    public static final String ACCT_SUBSTATUS_UNKNOWN = 'Unknown';
    public static final String ACCT_SUBSTATUS_INS_VERIFY = 'Insurance Verification';
    public static final String ACCT_SUBSTATUS_THIRD_PARTY = 'Third Party Payer';
    public static final String ACCT_SUBSTATUS_CREDIT = 'Credit';
    public static final String ACCT_SUBSTATUS_PAID = 'Paid';
    public static final String ACCT_SUBSTATUS_PREINVOICED = 'Pre-invoiced';

    private Constants() {}
}