/*
 * @author Sirono
 * @version 1.0.1
 * @Date: 05-03-2016
 * @description An apex page controller that exposes the site login functionality 
 * 
 * 14/09/2016 commented the code since it is not used into community/site for any business requirement 
 */
global with sharing class SiteLoginController {
/*  
    global String username {get; set;}
    global String password {get; set;}

    global PageReference login() {
        String startUrl = System.currentPageReference().getParameters().get('startURL');
        return Site.login(username, password, startUrl);
    }
*/
    global SiteLoginController() {
    }

}