.body, .pbBody, .headerRow, .pbBottomButtons, .contactBlock, .bPageBlock, .pbHeader .pbTitle h2.mainTitle{
	background-color: white !important;
	color: black;
}

.pbTitle {
	width:100% !important;
}

.pay-staff-tabale-left {
	width:48%;
	float:left;
	border: 0;
	margin-bottom: 20px;
}

.pay-staff-tabale-right {
	width:48%;
	float:right;
	border: 0;
	margin-bottom: 20px;
}

.pay-staff-lable{
	color: #4d4d4d;
	cursor: pointer;
	display: block;
	font-size: 0.875rem;
	font-weight: normal;
	margin-bottom: 0;
}

.pay-staff-input{
	-webkit-appearance: none;
	-moz-appearance: none;
	border-radius: 0;
	background-color: #fff;
	border-style: solid;
	border-width: 1px;
	border-color: #999;
	box-shadow: inset 0 1px 1px rgba(0,0,0,0.1);
	color: rgba(0,0,0,0.75);
	display: block;
	font-family: inherit;
	font-size: 0.875rem;
	height: 2.3125rem;
	margin: 0 0 1rem 0;
	/*margin: 0 0 1rem 0;
	padding: 0.5rem;*/
	width: 100%;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	box-sizing: border-box;
	-webkit-transition: border-color 0.15s linear, background 0.15s linear;
	-moz-transition: border-color 0.15s linear, background 0.15s linear;
	-ms-transition: border-color 0.15s linear, background 0.15s linear;
	-o-transition: border-color 0.15s linear, background 0.15s linear;
	transition: border-color 0.15s linear, background 0.15s linear;
}

.pay-staff-currency-prefix {
	background: #f2f2f2;
	border-right: none;
	color: #333;
	border-color: #999;
}

table { 
	border-collapse: collapse; 
}

.pay-staff-cg-detail-row {
	background-color: #fff;
	border:1px solid #999;
	font-size: 0.875rem;
	line-height: 2rem;
}
tr.pay-staff-cg-detail-row td{
	padding-left: 5px;
}

.pay-staff-cg-total-row {
	color: white !important;
	background-color: #7f7f7f;
	border-bottom: 0;
	box-shadow: 0 0 0 1px #7f7f7f;
	line-height: 30px;
	font-size: 13px;
}

tr.pay-staff-cg-total-row  td{
	padding-left: 5px;
	color: white !important;
}

.pay-staff-text-right {
	text-align: right !important;
}

.pay-staff-button {
	background: transparent !important;
	-webkit-appearance: none !important;
	-moz-appearance: none !important;
	border-radius: 0 !important;
	border-style: solid !important;
	border-width: 0 !important;
	cursor: pointer !important;
	font-family: "Fira Sans","Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif !important;
	font-weight: normal !important;
	line-height: normal !important;
	margin: 0 0 1.25rem !important;
	position: relative !important;
	text-align: center !important;
	text-decoration: none !important;
	display: inline-block !important;
	padding: 1rem 2rem 1.0625rem 2rem !important;
	font-size: 1rem !important;
	background-color: #0e85ac !important;
	border-color: #0b6a8a !important;
	color: #fff !important;
	transition: background-color 300ms ease-out !important;
}

.pay-staff-button {
	background-color: #0b6a8a !important;
}

.pay-staff-cancel-button {
	color: #333 !important;
	background-color: #b4b4b4 !important;
	border-color: #b4b4b4 !important;
}

.pay-staff-cancel-button:hover {
	background-color: #b4b4b4 !important;
}

.pay-staff-full-width {
	width: 100%;
}

.pay-staff-clear-both {
	clear: both;
}

.pay-staff-bottom-line {
	border: 1px solid #e1e1e1;
	margin-top: 10px;
    margin-bottom: 10px;
}

.pay-staff-message , .pbHeader .pbTitle h2.mainTitle{
	font-size: 1rem !important;
    font-weight: normal !important;
    line-height: 1.6 !important;
}

select.pay-staff-input {
	font-family: "Helvetica Neue","Helvetica",Helvetica,Arial,sans-serif;
    border-radius: 3px;
	padding-left: 10px;
	background-color: #FAFAFA;
	width: 100%;
}

.pay-staff-input:hover{
	background-color: #f3f3f3;
    border-color: gray;
}

.pay-staff-outer_block {
	z-index: 1000;
	margin: 0px;
	padding: 0px;
	width: 99%;
	height: 99%;
	top: 0px;
	border: 1px solid #fff;
	left: 0px;
	border-radius: 10px;
	opacity: 0.8;
	cursor: wait;
	position: fixed;
	background-color: Gray;
}

.pay-staff-inner_block{
	z-index: 1011;
	position: fixed;
	padding: 0px;
	margin: 0px;
	width: 30%;
	top: 40%;
	left: 35%;
	text-align: center;
	color: #fff;
	border: 1px solid #fff;
	border-radius: 10px;
	cursor: wait;
	background-color: #3F51B5;
	padding:10px;
	margin:10px;
}

span.pay-staff-custom_message{
	font-weight: bold;
	font-size: 12pt;
}

span.pay-staff-custom_message_2{
	
}

.pay-staff-output-label {
	width:100%;
	color:black;
	font-weight:bold;
}

.pay-staff-table-wrap {
    width: 100%;
}

.pay-staff-table-wrap table {
    width: 90%;
    table-layout: fixed;
}

.pay-staff-inner-table {
    max-height: 140px;
    overflow-y: auto;
}